CREATE TABLE MONTHS 
(
  MONTH_DISPLAY VARCHAR2(36) 
, MONTH_VALUE VARCHAR2(2) 
);

Insert into MONTHS (MONTH_DISPLAY,MONTH_VALUE) values ('JANUARY','01');
Insert into MONTHS (MONTH_DISPLAY,MONTH_VALUE) values ('FEBRUARY','02');
Insert into MONTHS (MONTH_DISPLAY,MONTH_VALUE) values ('MARCH','03');
Insert into MONTHS (MONTH_DISPLAY,MONTH_VALUE) values ('APRIL','04');
Insert into MONTHS (MONTH_DISPLAY,MONTH_VALUE) values ('MAY','05');
Insert into MONTHS (MONTH_DISPLAY,MONTH_VALUE) values ('JUNE','06');
Insert into MONTHS (MONTH_DISPLAY,MONTH_VALUE) values ('JULY','07');
Insert into MONTHS (MONTH_DISPLAY,MONTH_VALUE) values ('AUGUST','08');
Insert into MONTHS (MONTH_DISPLAY,MONTH_VALUE) values ('SEPTEMBER','09');
Insert into MONTHS (MONTH_DISPLAY,MONTH_VALUE) values ('OCTOBER','10');
Insert into MONTHS (MONTH_DISPLAY,MONTH_VALUE) values ('NOVEMBER','11');
Insert into MONTHS (MONTH_DISPLAY,MONTH_VALUE) values ('DECEMBER','12');

COMMIT;