create or replace FUNCTION CHECK_SALARY
(
  EMPLOYEE IN NUMBER, SALYEAR IN DATE, SALMONTH IN DATE, EMP_SAL IN NUMBER, YPOLOIPO IN NUMBER 
) RETURN BOOLEAN IS

vvSalary NUMBER;
vvYear NUMBER;
vvMonth NUMBER;

BEGIN

vvYear := TO_NUMBER(to_char(SALYEAR, 'YYYY'));
vvMonth := TO_NUMBER(to_char(SALMONTH,'MM'));

vvSalary := GET_SALARY(EMPLOYEE, vvYear, vvMonth, EMP_SAL);

IF vvSalary < YPOLOIPO THEN 
   RETURN FALSE;
ELSE
   RETURN TRUE;
END IF;

END;