CREATE TABLE REF_DOMAINS 
(
  DOMAIN VARCHAR2(50) 
, NAME VARCHAR2(60)
, SEQ NUMBER(5)
, MIN_VALUE VARCHAR2(50) 
, MAX_VAL_NUM NUMBER(5)
, MAX_VALUE VARCHAR2(50) 
);


INSERT INTO "XYLOLINE"."REF_DOMAINS" (DOMAIN, MAX_VALUE, SEQ, NAME) VALUES ('ORD_STATUS', '1', '10', 'Σε εξέλιξη')
INSERT INTO "XYLOLINE"."REF_DOMAINS" (DOMAIN, MAX_VALUE, SEQ, NAME) VALUES ('ORD_STATUS', '2', '20', 'Ολοκλήρωση')
INSERT INTO "XYLOLINE"."REF_DOMAINS" (DOMAIN, MAX_VALUE, SEQ, NAME) VALUES ('ORD_STATUS', '3', '30', 'Παράδωση')

commit;