CREATE TABLE ORDERS 
(
  ORD_ID NUMBER NOT NULL 
, ORD_CUST_ID NUMBER(18) NOT NULL 
, ORD_STATUS NUMBER(2) DEFAULT 1
, ORD_TOTAL NUMBER(8,2) 
, ORD_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE
, ORD_USER_NAME VARCHAR2(100) 
, ORD_TAGS VARCHAR2(4000) 
, ORD_COMMENTS VARCHAR2(4000)
, CONSTRAINT ORDERS_PK PRIMARY KEY 
  (
    ORD_ID 
  )
  ENABLE 
);

CREATE SEQUENCE ORDERS_SEQ START WITH 1 MINVALUE 1;

ALTER SEQUENCE ORDERS_SEQ NOCACHE;


ALTER TABLE ORDERS
ADD CONSTRAINT ORDERS_FK FOREIGN KEY
(
  ORD_CUST_ID 
)
REFERENCES CUSTOMERS
(
  CUST_ID 
)
ENABLE;

ALTER TABLE ORDERS
ADD CONSTRAINT ORDERS_CHK_TOTAL CHECK 
(ORD_TOTAL>=0)
ENABLE;

ALTER TABLE ORDERS 
DROP CONSTRAINT ORDERS_FK;

ALTER TABLE ORDERS
ADD CONSTRAINT ORDERS_CUST_FK FOREIGN KEY
(
  ORD_CUST_ID 
)
REFERENCES CUSTOMERS
(
  CUST_ID 
)
ON DELETE CASCADE ENABLE;



ALTER TABLE BALANCE
ADD CONSTRAINT BALANCE_ORDERS_FK FOREIGN KEY
(
  BA_ORD_ID 
)
REFERENCES ORDERS
(
  ORD_ID 
)
ON DELETE CASCADE ENABLE;


------------------------------ TRIGGER -----------------------------

 CREATE OR REPLACE TRIGGER ORDERS_BIU
  before insert or update ON ORDERS FOR EACH ROW
DECLARE
  order_id number;
BEGIN
  if inserting then  
    if :new.ord_id is null then
      select ORDERS_seq.nextval
        INTO order_id
        FROM dual;
      :new.ord_id := order_id;
    end if;
  end if;
END;


---------------------------------
